---
title: "COVID Mobility Analysis"
author: "Robert On"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Missing data

```{r eval=FALSE}
drake::readd(google_mob_fips) %>% 
  filter(is.na(fips5)) %>%
  filter(country_region_code == "US")
```

We were able to match all counties from the Google Mobility data set to FIPS codes from the US Census Bureau.

```{r}
drake::readd(google_mob_fill) %>%
  filter(country_region_code == "US") %>%
  group_by(country_region, sub_region_1, sub_region_2, value_type) %>%
  summarise(
    start_date = min(date),
    end_date = max(date),
    count = n(),
    prop_na = mean(is.na(value))) %>%
  filter(count != 85 | prop_na > 0)
```

We also ensured that missing data interpolation ensured consistent number of dates and no missing values.

```{r}
drake::readd(google_mob_cpt) %>%
  select(-data, -cpt_mdl) %>%
  summarise_if(~ is.numeric(.x) | lubridate::is.Date(.x) | lubridate::is.difftime(.x),
               list(missing = ~ mean(is.na(.x)), max = max, mean = mean, min = min),
               na.rm = TRUE) %>%
  gather()
```

## Reproducibility

```{r}
## datetime
Sys.time() 

## repository
git2r::repository()

## session info
sessionInfo()
```
