---
title: "Surveying the pandemic"
subtitle: "County Timeseries"
author: "Hal Varian, Robert On"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    code_folding: hide
  html_document:
    toc: yes
    df_print: paged
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

Loading required packages.

```{r include=FALSE}
# time series forecasting
library(fable)
# spike and slab time series
library(bsts)
# general data manipulation
library(tidyverse)
```

# Forecasting

## Univariate forecast

```{r}
covidcast_chr <- read_csv("https://ond3.com/covdata/covidcast_chr.csv",
                         col_types = cols(
                           geo_type = "c", geo_value = "c", date = "D",
                           county_name = "c", state_name = "c", state_abb = "c",
                           geocode = "c", subregion1_code = "c",
                           .default = col_number()))
```

```{r}
covid_ts <- covidcast %>%
  filter(geo_type == "county") %>%
  mutate(county_name = paste(county_name, state_abb, sep = ", ")) %>%
  select(-geo_type, -geo_value, -state_name, -state_abb, -geocode) %>%
  as_tsibble(key = county_name, index = date)
```

```{r}
fcst <- covid_ts %>% filter(date < "2020-04-01") %>%
  fill(jhu_csse_confirmed_incidence_num_value, .direction = "down") %>%
  select(jhu_csse_confirmed_incidence_num_value) %>%
  filter(county_name %in% c("New York County, NY",
                            "Essex County, NJ",
                            "Wayne County, MI",
                            "Santa Clara County, CA")) %>%
  model(
    ets = ETS(jhu_csse_confirmed_incidence_num_value),
    arima = ARIMA(jhu_csse_confirmed_incidence_num_value),
    rw = RW(jhu_csse_confirmed_incidence_num_value)
  ) %>%
  forecast(h = "1 week")

fcst %>% accuracy(covid_ts) %>% arrange(county_name, RMSE)

fcst %>%
  fabletools::autoplot(covid_ts %>% filter(date > "2020-03-01"), level = 95)
```

### Univariate predictive

```{r fig.height = 10}
covidcast_chr %>%
  select(date, county_name,
         starts_with("jhu_csse_confirmed_7dav_incidence_num_value"),
         matches("^.*survey_smoothed_.*cli_value")) %>%
  gather(metric, value, -date, -county_name) %>%
  filter(date > "2020-03-01") %>%
  filter(county_name %in% c(
    "Santa Clara County", "Contra Costa County", "Alameda County",
    "San Mateo County", "San Francisco County")) %>%
  ggplot((aes(date, value, color = metric))) + geom_line() +
  facet_grid(metric ~ county_name, scales = "free_y") +
  theme(legend.position = "none")
```

```{r}
fcst_dat <- covidcast_chr %>%
  select(date, county_name,
         starts_with("jhu_csse_confirmed_7dav_incidence_num_value"),
         matches("^.*survey_smoothed.*_cli_value")) %>%
  filter(complete.cases(.)) %>%
  group_by(county_name) %>%
  arrange(date)

fcst_3day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lead(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  google_survey_smoothed_cli_value,
     data = .)

fcst_7day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ google_survey_smoothed_cli_value,
     data = .)

fcst_14day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ google_survey_smoothed_cli_value,
     data = .)

fcst_3day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  fb_survey_smoothed_nohh_cmnty_cli_value,
     data = .)

fcst_7day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_nohh_cmnty_cli_value,
     data = .)

fcst_14day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_nohh_cmnty_cli_value,
     data = .)

fcst_3day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  fb_survey_smoothed_cli_value,
     data = .)

fcst_7day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_cli_value + county_name,
     data = .)

fcst_14day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_cli_value + county_name,
     data = .)


fcst_fe_3day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lead(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  google_survey_smoothed_cli_value + county_name,
     data = .)

fcst_fe_7day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ google_survey_smoothed_cli_value + county_name,
     data = .)

fcst_fe_14day_gg <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ google_survey_smoothed_cli_value + county_name,
     data = .)

fcst_fe_3day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  fb_survey_smoothed_nohh_cmnty_cli_value + county_name,
     data = .)

fcst_fe_7day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_nohh_cmnty_cli_value + county_name,
     data = .)

fcst_fe_14day_fb <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_nohh_cmnty_cli_value + county_name,
     data = .)

fcst_fe_3day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 3)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~  fb_survey_smoothed_cli_value + county_name,
     data = .)

fcst_fe_7day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 7)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_cli_value + county_name,
     data = .)

fcst_fe_14day_fb_hh <- fcst_dat %>%
  mutate_at(vars(contains("survey")), ~ lag(.x, 14)) %>%
  lm(jhu_csse_confirmed_7dav_incidence_num_value ~ fb_survey_smoothed_cli_value + county_name,
     data = .)
```

No county fixed effects:

```{r}
huxtable::huxreg("3day_gg" = fcst_3day_gg, "7day_gg" = fcst_7day_gg,
                 #"14day_gg" = fcst_14day_gg,
                 "3day_fb" = fcst_3day_fb, "7day_fb" = fcst_7day_fb,
                 #"14day_fb" = fcst_14day_fb,
                 "3day_fb_hh" = fcst_3day_fb_hh, "7day_fb_hh" = fcst_7day_fb_hh,
                 #"14day_fb_hh" = fcst_14day_fb_hh,
                
                 coefs = c(fb_hh = "fb_survey_smoothed_cli_value",
                           #fb_cmnty_hh = "fb_survey_smoothed_hh_cmnty_cli_value",
                           fb_cmnty = "fb_survey_smoothed_nohh_cmnty_cli_value",
                           goog_cmnty = "google_survey_smoothed_cli_value"),
                 statistics = c(N = "nobs", R2 = "r.squared"))
```

With county fixed effects:

```{r}
huxtable::huxreg("3day_fe_gg" = fcst_fe_3day_gg, "7day_fe_gg" = fcst_fe_7day_gg,
                 #"14day_fe_gg" = fcst_fe_14day_gg,
                 "3day_fe_fb" = fcst_fe_3day_fb, "7day_fe_fb" = fcst_fe_7day_fb,
                 #"14day_fe_fb" = fcst_fe_14day_fb,
                 "3day_fe_fb_hh" = fcst_fe_3day_fb_hh, "7day_fe_fb_hh" = fcst_fe_7day_fb_hh,
                 #"14day_fe_fb_hh" = fcst_fe_14day_fb_hh,
                 coefs = c(fb_hh = "fb_survey_smoothed_cli_value",
                           #fb_cmnty_hh = "fb_survey_smoothed_hh_cmnty_cli_value",
                           fb_cmnty = "fb_survey_smoothed_nohh_cmnty_cli_value",
                           goog_cmnty = "google_survey_smoothed_cli_value"),
                 statistics = c(N = "nobs", R2 = "r.squared"))
```
